### ISSUE TITLE
Test example doesn't work

### ISSUE THREAD

**Issue by Gargo** [iosphere/ISHPullUp#27]

**Comment by felixLam** [comment]
@Gargo can you provide a bit more context? 
Which version of Xcode did you use? The sample app requires Xcode 8.

**Comment by Gargo** [comment]
Ok. Then the problem is you should place info about xcode 8 somewhere to the top/bottom of readme in a separate section "System requirements". It is unreadable when it is written with a common font somewhere in the middle of the article

**Comment by felixLam** [comment]
Hi @Gargo, thank you for bringing this up. While it is mentioned in bold that it requires Swift 3, this could be a bit more prominent. 

> The sample app is written in Swift 3 and thus requires Xcode 8 to compile.
