### ISSUE TITLE
UITableview in bottom view controller 

### ISSUE THREAD

**Issue by HengdaXiao** [iosphere/ISHPullUp#32]
Hi,
Firstly, nice implementation.  Any solutions for scrolling tableview in the bottom view controller when it is in the expanded state?

Thanks!

**Comment by felixLam** [comment]
Hi, we have used it with a UICollectionView without issues. We manually calculate the maximum height. The top part (which remains visible when collapsed) should best not be scrollable.

**Comment by felixLam** [comment]
Can you be a bit more specific about the problem you are having?

**Comment by HengdaXiao** [comment]
@felixLam Thanks for the fast reply. After checking the example code. I think it is clear. I just close this issue.
