### ISSUE TITLE
Next version (1.0.4) published to Cocoapods.org?

### ISSUE THREAD

**Issue by JeffESchmitz** [iosphere/ISHPullUp#40]
Hello,

ISHPullUp is awesome - just what I've been looking for!

I would like to use this in a project that is also managing external dependencies through cocoa pods.

The current version published to www.cocoapods.org is 1.0.3. It is missing the latest changes to ISHPullUpViewController, notably the isLocked property.

Will there be an update to www.cocoapods.org soon so I don't have to add the ISH header files into my workspace project?

Thanks and keep up the good work!
Jeff

**Comment by shagedorn** [comment]
Thanks for the reminder. There shouldn't be anything stopping us from wrapping up the 1.04 release, we'll look into it shortly.

**Comment by shagedorn** [comment]
Hi Jeff, we have just pushed the new version. Please let us know should you have any issues with it!

**Comment by JeffESchmitz** [comment]
Thank you, I will pull latest. Appreciate the quick turn around!
