### ISSUE TITLE
[UIView setState:animated:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by VivienGiraud** [iosphere/ISHPullUp#42]
Hi,

This part of my code produce an error:

>     func pullUpViewController(_ pullUpViewController: ISHPullUpViewController, didChangeTo state: ISHPullUpState) {
        topLabel.text = textForState(state)
        handleView.setState(ISHPullUpHandleView.handleState(for: state), animated: firstAppearanceCompleted) //HERE
    }

I have this error:

>  -[UIView setState:animated:]: unrecognized selector sent to instance 0x7fb217b0b420
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setState:animated:]: unrecognized selector sent to instance 0x7fb217b0b420'
*** First throw call stack:

Any idea? I'm definitely lost :/

**Comment by felixLam** [comment]
If you create the handle view in code or nib make sure it is an instance of ISHPullUpHandleView.

**Comment by felixLam** [comment]
It seems that you instead of instantiating a ISHPullUpHandleView you created a standard UIView.

**Comment by felixLam** [comment]
Where do you create the view stored in handleView?

**Comment by VivienGiraud** [comment]
Like that ?

>  @IBOutlet private weak var handleView: ISHPullUpHandleView!

**Comment by VivienGiraud** [comment]
Yeah I thought the same thing at the beginning due to `[UIView setState:animated:]` instead of `[ISHPullUpHandleView setState:animated:]`.
But `ISHPullUpHandleView` is an instance of `UIView`.

**Comment by felixLam** [comment]
In interface builder you need to select ISHPullUpHandleView as the custom class for that view otherwise it will simply create a UIView for you. I don't have Xcode here right now. It is in somewhere in the right hand side inspector. You should only see the handle view correctly rendered in Interface Builder.

**Comment by felixLam** [comment]
ISHPullUpHandleView is a subclass of UIView

**Comment by VivienGiraud** [comment]
Yep sorry subclass not instance :)
I saw that I missed that custom class (ISHPullUpRoundedVisualEffectView) I add it but it doesn't change anything :(

**Comment by VivienGiraud** [comment]
Ok, so I had a view with that missing `ISHPullUpHandleView` custom class, I had to read the Storyboard file with Sublime Text to find it out.
Danke!

**Comment by felixLam** [comment]
Glad I could help
