### ISSUE TITLE
Do you have a pull down version of this control?

### ISSUE THREAD

**Issue by apwelsh** [iosphere/ISHPullUp#43]
Do you have a pull down version of this control?  If not, I would like to fork your project and create a pull down version.

**Comment by felixLam** [comment]
Hi @apwelsh, right now this is not supported. Better than a fork would be a PR that implements this as a property on `ISHPullUpViewController` (either an enum `direction` or a boolean property `invertedLayout`).

**Comment by apwelsh** [comment]
Sounds good.  I will work on that, since you are open to the idea.
