### ISSUE TITLE
BottomViewController BlackBox when using edgesForExtendedLayout

### ISSUE THREAD

**Issue by franckclement** [iosphere/ISHPullUp#44]
Hey,

I'm using a viewController navigation stack using edgesForExtendedLayout = [] to set the viewControllers layouts under the NavigationBar.

Using this line of code make a black box with the height of the navigationBar (44pt in portrait mode) at the bottom of the BottomViewController.

Removing this line make my UI under the navigationBar which is not expected either :)

Does anyone dealing with this issue ? or have a workaround ?

**Comment by felixLam** [comment]
Hi @franckclement,
can you reproduce this issue in the same app?
