### ISSUE TITLE
Cancel the `Intermediate` case

### ISSUE THREAD

**Issue by ugurcetinkaya** [iosphere/ISHPullUp#45]
I want to use only `up & down` status. If it is possible, how can I cancel the intermediate position?
Thanks

**Comment by felixLam** [comment]
Have you tried setting the snapThreshold to 0.5?

**Comment by felixLam** [comment]
You can also customize the behavior by returning one of the end positions in targetHeightForBottomViewController

**Comment by ugurcetinkaya** [comment]
Thank you for the response. I did second option
