### ISSUE TITLE
Set state of bottomVC

### ISSUE THREAD

**Issue by ugurcetinkaya** [iosphere/ISHPullUp#46]
Can I set `PullUpController` 's state programmatically? I want to assign initial state as `ISHPullUpStateExpanded`  when `PullUpController`  open?

Thanks

**Comment by abelondev** [comment]
I need the same.

**Comment by shagedorn** [comment]
Sorry for the late reply. Have you tried `- setState:animated:`? It should allow you to do what you want to achieve – please let us know if not.
