### ISSUE TITLE
Bottom blur removed while moving

### ISSUE THREAD

**Issue by VrasidasP** [iosphere/ISHPullUp#47]
When I'm moving the bottom view, the blur effect is lost (it becomes transparent and I can see the view below), and when I let go it appears correctly again.

Is this a bug or did I do something wrong while implementing this nice library?

Thanks!

**Comment by felixLam** [comment]
Can you reproduce the issue in the example app? Otherwise could you create a small sample that exposes the issue?

**Comment by VrasidasP** [comment]
I can see it works as it should in the example app.
Will look into it more (maybe something is not connected correctly).

**Comment by felixLam** [comment]
Will close this issue for now, feel free to re-open if you can provide more details about how you are using this framework.
