### ISSUE TITLE
Hide and Show the BottomView - pullupController.reloadData()?

### ISSUE THREAD

**Issue by andre991** [iosphere/ISHPullUp#48]
Hi, firstly congratulations, this framework is awesome.Please, I have some doubts:

1 - How can I show bottom view only after pressed an button and hide after pressed another button, if is possible?  

2- How can I update the view so that it can go through the delegates again(same tableView.reloadData())?

Thanks.

**Comment by shagedorn** [comment]
Thanks for your kind words.

1) Hiding the bottom view

The easiest way is to lock/collapse the bottom controller, and in your bottom view controller, adjust the minimum height in that case (unless you are using the lock state for other purposes, in which case you may introduce another state property). You can try this in the sample project.

Add this code to `ViewController.commonInit()`:

```
DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
    // lock/hide the bottom after 3 seconds
    self.isLocked = true
    self.setState(.collapsed, animated: true)

    DispatchQueue.main.asyncAfter(deadline: .now() + 3, execute: { 
        // unlock/show it again after another 3 seconds
        self.isLocked = false
        self.setState(.collapsed, animated:true)
    })
}
```

In the `BottomVC`, change this piece of code:

```
func pullUpViewController(_ pullUpViewController: ISHPullUpViewController, minimumHeightForBottomViewController bottomVC: UIViewController) -> CGFloat {
    // if locked, hide it completely
    return pullUpViewController.isLocked ? 0.0 : topView.systemLayoutSizeFitting(UILayoutFittingCompressedSize).height;
}
```

2) Assuming you are referring to the sizing delegate, calling `invalidateLayout` on the pull up controller should do. Alternatively, change the state, as done in the example above.

**Comment by andre991** [comment]
Thanks sharedorn, I will try. :)

**Comment by shagedorn** [comment]
Will close for now. Feel free to reopen in case something remains unclear.
