### ISSUE TITLE
Pull Handle hidden beneath tab bar in UITabBarController

### ISSUE THREAD

**Issue by reejosamuel** [iosphere/ISHPullUp#49]
If you wrap the container view controller inside a tab bar the pull up view is hidden under the tab bar

You can replicate the problem by changing the `ViewController.swift` with the following code
```
class ViewController: UITabBarController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.viewControllers = [OriginalViewController()]
    }
}

class OriginalViewController: ISHPullUpViewController {

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        commonInit()
    }

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        commonInit()
    }

    private func commonInit() {
        let storyBoard = UIStoryboard(name: "Main", bundle: nil)
        let contentVC = storyBoard.instantiateViewController(withIdentifier: "content") as! ContentVC
        let bottomVC = storyBoard.instantiateViewController(withIdentifier: "bottom") as! BottomVC
        contentViewController = contentVC
        bottomViewController = bottomVC
        bottomVC.pullUpController = self
        contentDelegate = contentVC
        sizingDelegate = bottomVC
        stateDelegate = bottomVC
    }
}
```

**Comment by reejosamuel** [comment]
Open a PR with a fix #50 here

**Comment by shagedorn** [comment]
@reejosamuel we have come up with a slightly more generic version. Could you please verify that [this](https://github.com/iosphere/ISHPullUp/pull/51) fixes your case? It does fix the provided sample. Thanks a lot for your effort in providing the sample and pointing at the right lines of code to adjut.

**Comment by reejosamuel** [comment]
@shagedorn Hi thanks for looking into it.  I think what you have added is a better solution since its more generic. I will go ahead and close my PR. Are you planning to bump the version soon?

**Comment by shagedorn** [comment]
Sure, just wanted to make sure it actually fixes your issue before bumping it. Will do it tomorrow in the office.

**Comment by shagedorn** [comment]
`1.0.5` has now been pushed :)

**Comment by razan-kA** [comment]
> If you wrap the container view controller inside a tab bar the pull up view is hidden under the tab bar
> 
> You can replicate the problem by changing the `ViewController.swift` with the following code
> 
> ```
> class ViewController: UITabBarController {
>     override func viewDidLoad() {
>         super.viewDidLoad()
>         
>         self.viewControllers = [OriginalViewController()]
>     }
> }
> 
> class OriginalViewController: ISHPullUpViewController {
> 
>     required init?(coder aDecoder: NSCoder) {
>         super.init(coder: aDecoder)
>         commonInit()
>     }
> 
>     override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
>         super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
>         commonInit()
>     }
> 
>     private func commonInit() {
>         let storyBoard = UIStoryboard(name: "Main", bundle: nil)
>         let contentVC = storyBoard.instantiateViewController(withIdentifier: "content") as! ContentVC
>         let bottomVC = storyBoard.instantiateViewController(withIdentifier: "bottom") as! BottomVC
>         contentViewController = contentVC
>         bottomViewController = bottomVC
>         bottomVC.pullUpController = self
>         contentDelegate = contentVC
>         sizingDelegate = bottomVC
>         stateDelegate = bottomVC
>     }
> }
> ```

i have just added the code, but still content of bottom View controller shows behind tab bar
