### ISSUE TITLE
Not working with SideMenu(SlideMenuControllerSwift)

### ISSUE THREAD

**Issue by shashank109** [iosphere/ISHPullUp#54]
Hello,
I am using SlideMenuControllerSwift in my app. When I use SlideMenuControllerSwift in my app pull up view won't show. If I don't use SlideMenuControllerSwift, its working fine. Can you please help me out to use this library with SlideMenuControllerSwift?

Thanks

**Comment by felixLam** [comment]
Sorry for the delay. Could you provide a minimum code example that shows the bug.

**Comment by shashank109** [comment]
Thanks for reply. Can you please send your mail id so that i can mail you code snippet?

**Comment by felixLam** [comment]
The easiest is probably if you create a public GitHub repository

**Comment by shashank109** [comment]
Its public repository and its accessible by others also. So providing your email would be more convenient and secure.

**Comment by felixLam** [comment]
Hi shahank, we will not be able to work with your actual project. Please provide a minimal demo project that replicates the issue.

**Comment by felixLam** [comment]
You can find more information about what a minimal demo project may look like here: http://sscce.org

**Comment by felixLam** [comment]
Closing for now. Feel free to open it again with a minimal code sample that illustrates the integration issue.
