### ISSUE TITLE
Can't set Title on ContentVC.

### ISSUE THREAD

**Issue by ItsMeMIHIR** [iosphere/ISHPullUp#56]
this function is for show

```
func Show()  {
    let storyBoard = UIStoryboard(name: "Main", bundle: nil)
    let contentVC = storyBoard.instantiateViewController(withIdentifier: "MenuMainViewController") as! MenuMainViewController
    let bottomVC = storyBoard.instantiateViewController(withIdentifier: "BottomVC") as! BottomVC
    contentVC.typeArray = categories
    contentVC.title  = "Menu" //***** this set title
    self.contentViewController = contentVC
    self.bottomViewController = bottomVC
    bottomVC.isPullUpController = self
    self.contentDelegate = contentVC
    self.sizingDelegate = bottomVC
    self.stateDelegate = bottomVC
}
```

and i am also try at "MenuMainViewController" 

```
override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Menu"
        
    }
```
both way i try both are not working

**Comment by felixLam** [comment]
If you want the title to be displayed in a Navigationsbar the content vc should be a navigation controller containing your actual vc. Or put the pull-up controller inside a navigation controller and set its title.

**Comment by felixLam** [comment]
Hello, unfortunately we are not able to provide "free support" for our open source libraries. If you believe that you encountered an issue in our library please provide a sample project that illustrates the issue. You can have a look at http://sscce.org to get a sense of what we need to investigate your issue.

As for the demo: A demo app ships with the library and is available here https://github.com/iosphere/ISHPullUp/tree/master/ISHPullUpSample

**Comment by ItsMeMIHIR** [comment]
see i created demo here
https://github.com/ItsMeMIHIR/ISHPullUpDemo

**Comment by shagedorn** [comment]
The project does not build in Xcode 8.3.3 after checkout.
