### ISSUE TITLE
Warnings in Xcode 9

### ISSUE THREAD

**Issue by KemalPajevic** [iosphere/ISHPullUp#67]
I have updated via CocoaPods to version 1.0.6, but I still get the "This block declaration is not a prototype" warning in **ISHPullUpViewController.m** (lines 406 and 457) for the missing void keyword. I can see that this issue was fixed in a commit a week ago, however it still seems to be present in the latest CocoaPods version.

**Comment by shagedorn** [comment]
We just released 1.0.7 which should be ready and warning-free for Xcode 9.2 and 9.3.
